version: "3.1"
services:
  db:
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
  web:
    volumes:
      - /data/www/Web/_Resources
    image: dimaip/1917distr:latest
    networks:
      - default
      - main
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.default.protocol=http"
        - "traefik.docker.network=main"
        - "traefik.frontend.rule=Host:pokayanie1917.ru,www.pokayanie1917.ru,dev.pokayanie1917.ru"
    ports:
      - '80'
    depends_on:
      - db
volumes:
  db-data:
secrets:
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
networks:
  main:
    external:
      name: main

