
Neos:
  Flow:
    session:
      inactivityTimeout: 604800
    i18n:
      defaultLocale: ru
    resource:
      collections:
        persistent:
          storage: s3PersistentResourcesStorage
          target: s3PersistentResourcesTarget
      storages:
        s3PersistentResourcesStorage:
          storage: 'Flownative\Aws\S3\S3Storage'
          storageOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'storage/1917/'
      targets:
        s3PersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'target/1917/'
            baseUri: 'https://psmb-neos-resources.hb.bizmrg.com/target/1917/'
  Neos:
    userInterface:
      defaultLanguage: ru
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 0
    fusion:
      autoInclude:
        Sfi.Site: true
  ContentRepository:
    contentDimensions:
      language:
        default: ru
        defaultPreset: ru
        label: Language
        icon: icon-language
        presets:
          ru:
            label: Russian
            values:
              - ru
            uriSegment: ''
          en:
            label: English
            values:
              - en
            uriSegment: en
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen'
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: '%env:AWS_ACCESS_KEY_ID%'
            secret: '%env:AWS_SECRET_ACCESS_KEY%'
          endpoint: 'https://hb.bizmrg.com'
